version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: grabpic-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: grabpic-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: grabpic-api
    ports:
      - "5050:5000"
    depends_on:
      - mongo
      - redis
      - ai
    env_file:
      - ./api-gateway/.env

  worker:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.worker
    container_name: grabpic-worker
    depends_on:
      - mongo
      - redis
      - ai
    env_file:
      - ./api-gateway/.env

  ai:
    build:
      context: ./ai-service
    container_name: grabpic-ai
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./ai-service/.env

volumes:
  mongo_data:
